version: "3.1"
services:
  pdf_service:
    build:
      context: .
      dockerfile: local/docker/pdfOffline.Dockerfile
    volumes:
      - .:/app:cached
    entrypoint: "bash -c 'yarn run start'"
    ports:
      - 3009:3009
      - 4569:4569